# Generated by Django 2.2.1 on 2019-06-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
