# Generated by Django 2.2.1 on 2019-05-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
