# Generated by Django 2.2.1 on 2019-05-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_like_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='(Hold down the Ctrl(Windows)/Command(Mac) button to select multiple options) ', related_name='recipes', to='ingredients.Ingredient'),
        ),
    ]
