# Generated by Django 2.2.1 on 2019-06-27 15:32

from django.db import migrations


def migrate_image(apps, schema_editor):
    Recipe = apps.get_model('recipes', 'Recipe')
    RecipeImage = apps.get_model('recipes', 'RecipeImage')
    Image = apps.get_model('recipes', 'Image')
    for recipe in Recipe.objects.filter(image__isnull=False):
        image = Image.objects.create(image=recipe.image)
        RecipeImage.objects.create(recipe=recipe, image=image)


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0005_add_recipe_image_models'),
    ]

    operations = [
        migrations.RunPython(migrate_image, reverse_code=migrations.RunPython.noop),
    ]
