# Generated by Django 2.2.1 on 2019-06-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20190515_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=1),
        ),
    ]
