# Generated by Django 2.2.1 on 2019-06-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20190611_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
