# Generated by Django 2.2.2 on 2019-06-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='view_count',
        ),
    ]
